<?php

namespace App\Controllers;
use App\Models\AFCModel;
use CodeIgniter\HTTP\RedirectResponse;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class AFCController extends BaseController{
    private AFCModel $afc;
    protected object $conditions;
    protected array $data;
    protected array $dates;
    protected array $datesFull;
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->afc= model(AFCModel::class);
        $this->conditions= (object)[
            "college"=>"specLevel IN ('СПО-повышенный уровень','СПО-базовый уровень','НПО (лицей, гимназия)')",
            "vpo"=>"specLevel IN ('ВПО-Специалисты','ВПО-Бакалавры','ВПО-Магистры')",
            "ppo"=>"specLevel IN ('Аспирантура','Докторантура')",
        ];
        $this->dates = $this->model->get_dates('2024-06-20', date("Y-m-d"),"d.m");
        $this->datesFull = $this->model->get_dates('2024-06-20', date("Y-m-d"),"Y-m-d");
    }

    public function test(){
        $data= (object)[];

        $data->specs= $this->afc->getAFC(["specName","specProfile"],false,false,false,["specCode!="=>""],'specName',false);
        $this->afc->getValuesByList($data->specs,"codes",["specName","specProfile"],["specCode","COUNT(id) as cnt"],["specCode"]);
        $this->afc->getValuesByList($data->specs,"forms",["specName","specProfile"],["specShape","COUNT(id) as cnt"],["specCode"]);
        $this->afc->getValuesByList($data->specs,"levels",["specName","specProfile"],["specLevel","COUNT(id) as cnt"],["specCode"]);

        //$data->specs= $this->afc->getAFC("specCode",["specLevel","specShape","specName","specProfile"],false,false,["specCode!="=>""],'specCode',false);

        $data->totalApp= $this->afc->db->table($this->afc->table)->get()->getNumRows();
        $data->methodSubmitting= (object)[
            "total"=> $this->afc->getAFC("methodSubmitting",false,false,false,["methodSubmitting!="=>""],false,['methodSubmitting']),
//            "byDate"=> $this->afc->getAFC("methodSubmitting",false,true,false,["methodSubmitting!="=>""],false,['methodSubmitting']),
//          "byDateTime"=> $this->afc->getAFC("methodSubmitting",false,false,true,["methodSubmitting!="=>""],false,['methodSubmitting']),
        ];
        $data->edForms= (object)[
            "total"=> $this->afc->getAFC("specShape",false,false,false,["specShape!="=>""],false,['specShape']),
//            "byDate"=> $this->afc->getAFC("specShape",false,true,false,["specShape!="=>""],false,['specShape']),
//            "byDateTime"=> $this->afc->getAFC("specShape",false,false,true,["specShape!="=>""],false,['specShape']),
        ];

        $data->levels= $this->afc->getAFC("specLevel",false,false,false,false,false,false);
        $data->basis= $this->afc->getAFC("appBasis",false,false,false,["appBasis!="=>""],false,['appBasis']);
        $data->appStatus= $this->afc->getAFC("appStatus",false,false,false,false,false,false);
        $data->citizenship= $this->afc->getAFC("citizenship",false,false,false,false,false,false);
        $data->uStatus= $this->afc->getAFC("uStatus",false,false,false,false,false,false);
        $data->approval= $this->afc->getAFC("approval",false,false,false,false,false,false);

        return view("public/afc/Main",(array)$data);

    }

    public function summary():string|bool
    {

        $data= (object)[
            "titles"=> (object)[
                'all'=> "Всего",
                'college'=> "Колледжи",
                'vpo'=> "ВПО",
                'ppo'=> "ППО",
            ],
            "totals"=>(object)[
                "apps"=> (object)[],
                "uIDs"=> (object)[],
            ],
            "mSubmit"=> (object)[],
            "specProfiles"=>(object)[],
            "specs"=>(object)[],
        ];
        $data->totals->apps->all= $this->afc->getAFCCount("id");
        foreach ($this->conditions as $code=>$condition)
            $data->totals->apps->{$code}= $this->afc->getAFCCount("id",$condition);

        $pageContent["appTotals"]= view("public/afc/ChartTotals",[
            "chartID"=>"appTotals",
            "chartTitle"=>"Заявки",
            "labels"=> $data->titles,
            "values"=> $data->totals->apps,
            "dLabels"=> $this->afc->prepareDate($data->titles),
            "dValues"=> $this->afc->prepareDate($data->totals->apps),
            "width"=>"100%",
            "height"=>"150px",
        ]);

        $data->totals->uIDs->all= $this->afc->getAFCCount("uID");
        foreach ($this->conditions as $code=>$condition)
            $data->totals->uIDs->{$code}= $this->afc->getAFCCount("uID",$condition);

        $pageContent["abitTotals"]= view("public/afc/ChartTotals",[
            "chartID"=>"abitTotals",
            "chartTitle"=>"Люди",
            "labels"=> $data->titles,
            "values"=> $data->totals->uIDs,
            "dLabels"=> $this->afc->prepareDate($data->titles),
            "dValues"=> $this->afc->prepareDate($data->totals->uIDs),
            "width"=>"100%",
            "height"=>"150px",
            "kl"=>false
        ]);

        foreach ($this->conditions as $code=>$condition){
            $labels= [];
            $this->afc->prepareArrays(
                $data->mSubmit->{$code},
                $labels,
                $this->afc->getAFC("methodSubmitting",false,"methodSubmitting!='' AND $condition",false,false,false,['methodSubmitting']),
                "methodSubmitting"
            );
            $pageContent["methodSubmitting"][$code]= view("public/afc/ChartTotals",[
                "chartID"=>"ms_$code",
                "chartTitle"=>$data->titles->{$code},
                "labels"=> $labels,
                "values"=> (object)$data->mSubmit->{$code},
                "dLabels"=> $this->afc->prepareDate($labels),
                "dValues"=> $this->afc->prepareDate($data->mSubmit->{$code}),
                "kl"=> true,
                "width"=>"100%",
                "height"=>"150px",
            ]);
        }

        foreach ($this->conditions as $code=>$condition){
            $labels= [];
            $this->afc->prepareArrays(
                $list,
                $labels,
                $this->afc->getAFC("specShape",false,"specShape!='' AND $condition",false,false,false,['specShape']),
                "specShape"
            );
            $pageContent["forms"][$code]= view("public/afc/ChartTotals",[
                "chartID"=>"form_$code",
                "chartTitle"=>$data->titles->{$code},
                "labels"=> $labels,
                "values"=> (object)$list,
                "dLabels"=> $this->afc->prepareDate($labels),
                "dValues"=> $this->afc->prepareDate($list),
                "kl"=> true,
                "width"=>"100%",
                "height"=>"150px",
            ]);
        }

        $basis= [];
        $this->afc->prepareArrays(
            $basis,
            $labels,
            $this->afc->getAFC("appBasis",false,["appBasis!="=>""]),
            "appBasis"
        );
        $pageContent["appBasis"]= view("public/afc/ChartTotals",[
            "chartID"=>"appBasis",
            "chartTitle"=>"Основание",
            "labels"=> $labels,
            "values"=> (object)$basis,
            "dLabels"=> $this->afc->prepareDate($labels),
            "dValues"=> $this->afc->prepareDate($basis),
            "width"=>"100%",
            "height"=>"150px",
            "kl"=>true
        ]);


        $data->specProfiles=[
            'college'=> (object)[
                "title"=> "Колледжи",
                "list" => $this->afc->getAFC(["specName","specProfile"],['specID'],"specLevel IN ('СПО-повышенный уровень','СПО-базовый уровень','НПО (лицей, гимназия)')",'specName')
            ],
            'vpo'=> (object)[
                "title"=> "ВПО",
                "list" => $this->afc->getAFC(["specName","specProfile"],['specID'],"specLevel IN ('ВПО-Специалисты','ВПО-Бакалавры','ВПО-Магистры')",'specName')
            ],
            'ppo'=> (object)[
                "title"=> "ППО",
                "list" => $this->afc->getAFC(["specName","specProfile"],['specID'],"specLevel IN ('Аспирантура','Докторантура')",'specName')
            ],
        ];
        $pageContent["specProfiles"]= view("public/afc/SpecsList",["list"=>$data->specProfiles]);

        return  view("public/page",["pageContent"=>view("public/afc/Main",$pageContent)]);
    }

    public function chartSpecByDays($specID):string|bool
    {
        $spec= $this->afc->db
            ->table($this->afc->table)
            ->select(["specName","specProfile"])
            ->where("specID",$specID)
            ->get()->getFirstRow("array");
        $totalRows= $this->afc->getAFC(["appDate"],false,$spec,"appDateTime",true);
        $formKeys= $this->afc->getAFC(["specShape"],false,$spec,"appDateTime");
        $formRows= $this->afc->getAFC(["appDate","specShape"],false,$spec,"appDateTime",true,"specShape",false);
        $levelKeys= $this->afc->getAFC(["specLevel"],false,$spec,"appDateTime");
        $levelRows= $this->afc->getAFC(["appDate","specLevel"],false,$spec,"appDateTime",true,"specLevel",false);

        $totals= [];
        $forms= [];
        $levels= [];
        /*
                $this->dates= [];
                foreach ($totalRows as $day=>$total){
                    $this->dates[]= $day;
                    $totals[$day]= $total??0;
                    foreach ($formKeys as $key=>$row)
                        $forms[$key][$day]= $formRows[$day][$row->specShape]??0;
                    foreach ($levelKeys as $key=>$row)
                        $levels[$key][$day]= $levelRows[$day][$row->specLevel]??0;
                }
        */
        foreach ($this->dates as $dk=>$day){
            $this->dates[$dk]= "'$day'";
            $totals[$day]= $totalRows[$day]??0;
            foreach ($formKeys as $key=>$row)
                $forms[$key][$day]= $formRows[$day][$row->specShape]??0;
            foreach ($levelKeys as $key=>$row)
                $levels[$key][$day]= $levelRows[$day][$row->specLevel]??0;
        }
        $formColors= [];
        foreach ($formKeys as $key=>$row){
            $formColors[$key]= $this->model->colors[$row->specShape];
        }

        $levelColors= [];
        foreach ($levelKeys as $key=>$row){
            $levelColors[$key]= $this->model->colors[$row->specLevel];
        }

        $data= [
            "spec"=> (object)$spec,
            "dates"=>implode(",",$this->dates),
            "totals"=>$totals,
            "formTitles"=>$formKeys,
            "forms"=>$forms,
            "levelTitles"=>$levelKeys,
            "levels"=>$levels,
            "formColors"=>$formColors,
            "levelColors"=>$levelColors,
            "formRows"=>$formRows,
            "levelRows"=>$levelRows,
        ];
        $pageContent= view("public/afc/SpecChart",$data);

        return  view("public/page",["pageContent"=>$pageContent]);
    }
    public function byDays($type= false):string|bool{
        if(!$type) return false;
//        echo $type;

        switch ($type){
            case "ms_vpo":
                $list= $this->afc->getAFC(
                    ["methodSubmitting","appDate"],
                    false,
                    $this->conditions->{"vpo"},
                    "appDate"
                );
                $treeFD= $this->afc->convertListToTreeFieldDate($list,"methodSubmitting");
                $treeDF= $this->afc->convertListToTreeFieldDate($list,"methodSubmitting",true);
                dd($treeFD);
                $colors=["#FFB800","#B90085","#007C23"];
                //dd($this->model->colors);

                $max= 0;
                foreach ($treeFD as $code=>$row){
                    $treeFD[$code]= $this->afc->fillMissingDates($this->datesFull,$row);
                    $max = ($max>max($row))?$max:max($row);
                }
                $max= ceil($max*1.05);
                $values=[];
                foreach ($treeFD as $code=>$row)
                    $values[$code]= implode(",",$row);

                $this->data['pageContent']= view("public/afc/ChartByDays",[
                    "chartTitle"=>"Способ подачи: ВПО",
                    "colors"=> $colors,
                    "dates"=> $this->dates,
                    "datasets"=> $values,
                    "details"=> $treeDF,
                    "max"=> $max+1,
                ]);
                break;
            case "appTotals":
                $college= $this->afc->getAFC(
                    ["appDate"],
                    false,
                    $this->conditions->college,
                    "appDate"
                );
                $vpo= $this->afc->getAFC(
                    ["appDate"],
                    false,
                    $this->conditions->vpo,
                    "appDate"
                );
                $ppo= $this->afc->getAFC(
                    ["appDate"],
                    false,
                    $this->conditions->ppo,
                    "appDate"
                );

                $treeFD['Колледжи']= $this->afc->convertListToTreeFieldDate($college,false);
                $treeFD['ВПО']= $this->afc->convertListToTreeFieldDate($vpo,false);
                $treeFD['ППО']= $this->afc->convertListToTreeFieldDate($ppo,false);

                $colors=["#Fx1FB800","#B90085","#007C23"];
                $max= 0;

                foreach ($treeFD as $code=>$row){
                    if(!empty($row))
                        $max = ($max>max($row))?$max:max($row);
                    $treeFD[$code]= $this->afc->fillMissingDates($this->datesFull,$row);
                }
                $max= ceil($max*1.05);
                $values=[];
                foreach ($treeFD as $code=>$row)
                    $values[$code]= implode(",",$row);

                $this->data['pageContent']= view("public/afc/ChartByDays",[
                    "chartTitle"=>"Способ подачи: ВПО",
                    "colors"=> $colors,
                    "dates"=> $this->dates,
                    "datasets"=> $values,
//                    "details"=> $treeDF,
                    "max"=> $max+1,
                ]);
                break;
        }
        return  view("public/page",$this->data);
    }

    public function specList():string
    {
        $results=[
            'spo_b'=> (object)[
                "title"=> "СПО-базовый уровень",
                "list" => []
            ],
            'spo_u'=> (object)[
                "title"=> "СПО-повышенный уровень",
                "list" => []
            ],
            'npo'=> (object)[
                "title"=> "НПО (лицей, гимназия)",
                "list" => []
            ],
            'bak'=> (object)[
                "title"=> "Бакалавры",
                "list" => []
            ],
            'spec'=> (object)[
                "title"=> "Специалисты",
                "list" => []
            ],
            'mag'=> (object)[
                "title"=> "Магистры",
                "list" => []
            ],
            'asp'=> (object)[
                "title"=> "Аспирантура",
                "list" => []
            ],
            'doc'=> (object)[
                "title"=> "Докторантура",
                "list" => []
            ],
        ];

        $arr= (object)[
            "spo_b"=>[4],
            "spo_u"=>[5],
            "npo"=>[6],
            "bak"=>[2],
            "spec"=>[1],
            "mag"=>[3],
            "asp"=>[7],
            "doc"=>[8],
        ];

        foreach ($arr as $code=>$whereIn){
            $list= $this->db
                ->table("edSpecs")
                ->select("code, name, profile, edLevel, SUM(cnt) cnt, SUM(places) places")
                ->whereIn("edLevel",$whereIn)
                ->groupBy(['code','name',"profile",'edLevel'])
                ->orderBy("edLevel","asc")
                ->orderBy("name","asc")
                ->orderBy("profile","asc")
                ->get()
                ->getResult();

            $specs= [];

            foreach ($list as $spec){
                if(!isset($specs[$spec->name]))
                    $specs[$spec->name]= (object)[
                        "name"      =>  $spec->name,
                        "code"      =>  $spec->code,
                        "places"    =>  0,
                        "cnt"       =>  0,
                        "list"      =>  []
                    ];
                $specs[$spec->name]->places +=  $spec->places;
                $specs[$spec->name]->cnt    +=  $spec->cnt;
                $specs[$spec->name]->list[] =   $spec;
            }

            $results[$code]->list= $specs;
        }
        $edLevels= [];
        $res= $this->db->table("edLevels")->get()->getResult();
        foreach ($res as $row)
            $edLevels[$row->id]= $row->name;

        $pageContent["specProfiles"]= view("public/afc/SpecsList2",["list"=>$results,"edLevels"=>$edLevels,"showSpec"=>true]);

        return  view("public/page",["pageContent"=>view("public/afc/Main",$pageContent)]);
    }
}