<?php

namespace App\Controllers;
use App\Models\AFCModel;
use CodeIgniter\HTTP\RedirectResponse;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class AFCController extends BaseController{
    private AFCModel $afc;
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->afc= model(AFCModel::class);
    }

    public function test(){
        $data= (object)[];


        $data->specs= $this->afc->getAFC(["specName","specProfile"],false,false,false,["specCode!="=>""],'specName',false);
        $this->afc->getValuesByList($data->specs,"codes",["specName","specProfile"],["specCode","COUNT(id) as cnt"],["specCode"]);
        $this->afc->getValuesByList($data->specs,"forms",["specName","specProfile"],["specShape","COUNT(id) as cnt"],["specCode"]);
        $this->afc->getValuesByList($data->specs,"levels",["specName","specProfile"],["specLevel","COUNT(id) as cnt"],["specCode"]);

        //$data->specs= $this->afc->getAFC("specCode",["specLevel","specShape","specName","specProfile"],false,false,["specCode!="=>""],'specCode',false);

        $data->totalApp= $this->afc->db->table($this->afc->table)->get()->getNumRows();
        $data->methodSubmitting= (object)[
            "total"=> $this->afc->getAFC("methodSubmitting",false,false,false,["methodSubmitting!="=>""],false,['methodSubmitting']),
//            "byDate"=> $this->afc->getAFC("methodSubmitting",false,true,false,["methodSubmitting!="=>""],false,['methodSubmitting']),
//          "byDateTime"=> $this->afc->getAFC("methodSubmitting",false,false,true,["methodSubmitting!="=>""],false,['methodSubmitting']),
        ];
        $data->edForms= (object)[
            "total"=> $this->afc->getAFC("specShape",false,false,false,["specShape!="=>""],false,['specShape']),
//            "byDate"=> $this->afc->getAFC("specShape",false,true,false,["specShape!="=>""],false,['specShape']),
//            "byDateTime"=> $this->afc->getAFC("specShape",false,false,true,["specShape!="=>""],false,['specShape']),
        ];

        $data->levels= $this->afc->getAFC("specLevel",false,false,false,false,false,false);
        $data->basis= $this->afc->getAFC("appBasis",false,false,false,["appBasis!="=>""],false,['appBasis']);
        $data->appStatus= $this->afc->getAFC("appStatus",false,false,false,false,false,false);
        $data->citizenship= $this->afc->getAFC("citizenship",false,false,false,false,false,false);
        $data->uStatus= $this->afc->getAFC("uStatus",false,false,false,false,false,false);
        $data->approval= $this->afc->getAFC("approval",false,false,false,false,false,false);

        return view("public/afc/Main",(array)$data);

    }

    public function summary():string|bool
    {
        $conditions= (object)[
            "college"=>"specLevel IN ('СПО-повышенный уровень','СПО-базовый уровень','НПО (лицей, гимназия)')",
            "vpo"=>"specLevel IN ('ВПО-Специалисты','ВПО-Бакалавры','ВПО-Магистры')",
            "ppo"=>"specLevel IN ('Аспирантура','Докторантура')",
        ];

        $data= (object)[
            "titles"=> (object)[
                'all'=> "Всего",
                'college'=> "Колледжи",
                'vpo'=> "ВПО",
                'ppo'=> "ППО",
            ],
            "totals"=>(object)[
                "apps"=> (object)[],
                "uIDs"=> (object)[],
            ],
            "mSubmit"=> (object)[],
            "specProfiles"=>(object)[],
            "specs"=>(object)[],
        ];
        $data->totals->apps->all= $this->afc->getAFCCount("id");
        foreach ($conditions as $code=>$condition)
            $data->totals->apps->{$code}= $this->afc->getAFCCount("id",$condition);

        $pageContent["appTotals"]= view("public/afc/ChartTotals",[
            "chartID"=>"appTotals",
            "chartTitle"=>"Заявки",
            "labels"=> $data->titles,
            "values"=> $data->totals->apps,
            "dLabels"=> $this->afc->prepareDate($data->titles),
            "dValues"=> $this->afc->prepareDate($data->totals->apps),
            "width"=>"100%",
            "height"=>"150px",
        ]);

        $data->totals->uIDs->all= $this->afc->getAFCCount("uID");
        foreach ($conditions as $code=>$condition)
            $data->totals->uIDs->{$code}= $this->afc->getAFCCount("uID",$condition);

        $pageContent["abitTotals"]= view("public/afc/ChartTotals",[
            "chartID"=>"abitTotals",
            "chartTitle"=>"Люди",
            "labels"=> $data->titles,
            "values"=> $data->totals->uIDs,
            "dLabels"=> $this->afc->prepareDate($data->titles),
            "dValues"=> $this->afc->prepareDate($data->totals->uIDs),
            "width"=>"100%",
            "height"=>"150px",
            "kl"=>false
        ]);

        foreach ($conditions as $code=>$condition){
            $labels= [];
            $this->afc->prepareArrays(
                $data->mSubmit->{$code},
                $labels,
                $this->afc->getAFC("methodSubmitting",false,"methodSubmitting!='' AND $condition",false,false,false,['methodSubmitting']),
                "methodSubmitting"
            );
            $pageContent["methodSubmitting"][$code]= view("public/afc/ChartTotals",[
                "chartID"=>"ms_$code",
                "chartTitle"=>$data->titles->{$code},
                "labels"=> $labels,
                "values"=> (object)$data->mSubmit->{$code},
                "dLabels"=> $this->afc->prepareDate($labels),
                "dValues"=> $this->afc->prepareDate($data->mSubmit->{$code}),
                "kl"=> true,
                "width"=>"100%",
                "height"=>"150px",
            ]);
        }

        foreach ($conditions as $code=>$condition){
            $labels= [];
            $this->afc->prepareArrays(
                $list,
                $labels,
                $this->afc->getAFC("specShape",false,"specShape!='' AND $condition",false,false,false,['specShape']),
                "specShape"
            );
            $pageContent["forms"][$code]= view("public/afc/ChartTotals",[
                "chartID"=>"form_$code",
                "chartTitle"=>$data->titles->{$code},
                "labels"=> $labels,
                "values"=> (object)$list,
                "dLabels"=> $this->afc->prepareDate($labels),
                "dValues"=> $this->afc->prepareDate($list),
                "kl"=> true,
                "width"=>"100%",
                "height"=>"150px",
            ]);
        }

        $basis= [];
        $this->afc->prepareArrays(
            $basis,
            $labels,
            $this->afc->getAFC("appBasis",false,["appBasis!="=>""]),
            "appBasis"
        );
        $pageContent["appBasis"]= view("public/afc/ChartTotals",[
            "chartID"=>"appBasis",
            "chartTitle"=>"Основание",
            "labels"=> $labels,
            "values"=> (object)$basis,
            "dLabels"=> $this->afc->prepareDate($labels),
            "dValues"=> $this->afc->prepareDate($basis),
            "width"=>"100%",
            "height"=>"150px",
            "kl"=>true
        ]);


        $data->specProfiles=[
            'college'=> (object)[
                "title"=> "Колледжи",
                "list" => $this->afc->getAFC(["specName","specProfile"],['specID'],"specLevel IN ('СПО-повышенный уровень','СПО-базовый уровень','НПО (лицей, гимназия)')",'specName')
            ],
            'vpo'=> (object)[
                "title"=> "ВПО",
                "list" => $this->afc->getAFC(["specName","specProfile"],['specID'],"specLevel IN ('ВПО-Специалисты','ВПО-Бакалавры','ВПО-Магистры')",'specName')
            ],
            'ppo'=> (object)[
                "title"=> "ППО",
                "list" => $this->afc->getAFC(["specName","specProfile"],['specID'],"specLevel IN ('Аспирантура','Докторантура')",'specName')
            ],
        ];
        $pageContent["specProfiles"]= view("public/afc/SpecsList",["list"=>$data->specProfiles]);

        return  view("public/page",["pageContent"=>view("public/afc/Main",$pageContent)]);
    }

    public function chartSpecByDays($specID):string|bool
    {
        $spec= $this->afc->db
            ->table($this->afc->table)
            ->select(["specName","specProfile"])
            ->where("specID",$specID)
            ->get()->getFirstRow("array");
        $totalRows= $this->afc->getAFC(["appDate"],false,$spec,"appDateTime",true);
        $formKeys= $this->afc->getAFC(["specShape"],false,$spec,"appDateTime");
        $formRows= $this->afc->getAFC(["appDate","specShape"],false,$spec,"appDateTime",true,"specShape",false);
        $levelKeys= $this->afc->getAFC(["specLevel"],false,$spec,"appDateTime");
        $levelRows= $this->afc->getAFC(["appDate","specLevel"],false,$spec,"appDateTime",true,"specLevel",false);

        $totals= [];
        $forms= [];
        $levels= [];
        /*
                $dates= [];
                foreach ($totalRows as $day=>$total){
                    $dates[]= $day;
                    $totals[$day]= $total??0;
                    foreach ($formKeys as $key=>$row)
                        $forms[$key][$day]= $formRows[$day][$row->specShape]??0;
                    foreach ($levelKeys as $key=>$row)
                        $levels[$key][$day]= $levelRows[$day][$row->specLevel]??0;
                }
        */
        $dates = $this->model->get_dates('2024-06-20', date("Y-m-d"),"d.m");
        foreach ($dates as $dk=>$day){
            $dates[$dk]= "'$day'";
            $totals[$day]= $totalRows[$day]??0;
            foreach ($formKeys as $key=>$row)
                $forms[$key][$day]= $formRows[$day][$row->specShape]??0;
            foreach ($levelKeys as $key=>$row)
                $levels[$key][$day]= $levelRows[$day][$row->specLevel]??0;
        }
        $formColors= [];
        foreach ($formKeys as $key=>$row){
            $formColors[$key]= $this->model->colors[$row->specShape];
        }

        $levelColors= [];
        foreach ($levelKeys as $key=>$row){
            $levelColors[$key]= $this->model->colors[$row->specLevel];
        }

        $dates= implode(",",$dates);
        $data= [
            "spec"=> (object)$spec,
            "dates"=>$dates,
            "totals"=>$totals,
            "formTitles"=>$formKeys,
            "forms"=>$forms,
            "levelTitles"=>$levelKeys,
            "levels"=>$levels,
            "formColors"=>$formColors,
            "levelColors"=>$levelColors,
            "formRows"=>$formRows,
            "levelRows"=>$levelRows,
        ];
        $pageContent= view("public/afc/SpecChart",$data);

        return  view("public/page",["pageContent"=>$pageContent]);
    }


}