<?php

namespace App\Controllers;

use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;
use App\Models\AFCModel;

class AFCSpec extends BaseController
{
    protected array $data;
    protected array $dates;
    protected array $datesFull;

    private AFCModel $afc;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger):void
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->afc = model(AFCModel::class);
        $this->dates = $this->model->get_dates('2024-06-20', date("Y-m-d"), "d.m");
        $this->datesFull = $this->model->get_dates('2024-06-20', date("Y-m-d"), "Y-m-d");
    }

    public function list(): string
    {
        /* get forms */
        $forms= $this->db
            ->table("edForms")
            ->get()
            ->getResult();

        $this->model->setArrayKey($forms);

        /* get levels */
        $levels= $this->db
            ->table("edLevels")
            ->orderBy("sort","ASC")
            ->get()
            ->getResult();

        $this->model->setArrayKey($levels);

        /* get specialities */
        $specs= [];
        foreach ($levels as $level){
            $specs[$level->id]= (object)[
                "level" =>  $level,
                "list"  =>  $this->db
                    ->table("edSpecs")
                    ->join(
                        "dataSpec",
                        "dataSpec.op=edSpecs.id",
                        "left"
                    )
                    ->where("edLevel", $level->id)
                    ->where("places>", 0)
                    ->where("dataSpec.day","all")
                    ->orderBy("name")
                    ->orderBy("profile")
                    ->orderBy("profile")
                    ->orderBy("edForm")
                    ->get()
                    ->getResult()
            ];

            $this->model->replacementByRefers($specs[$level->id]->list,"edForm",$forms);

            $this->afc->buildSpecsTree($specs[$level->id]->list);

        }
        /* show specialities */
        $pageContent= view("public/AFC/Specs/List",[
            "list"          => $specs,
        ]);


        $includes=(object)[
            'js'=>[
                "js/public/specs-filter.js"
            ],
            'css'=>[
                "css/public/spec-list.css"
            ],
        ];

        return view("public/page",[
            "pageContent"   =>  $pageContent,
            "includes"      =>  $includes,
        ]);
    }

    public function detail($type,$id):string
    {

        $forms= $this->db
            ->table("edForms")
            ->get()
            ->getResult();

        $forms= $this->model->prepareList($forms,"id");

        $specs= $this->db
            ->table("edSpecs")
            ->select("id,code,edForm,edLevel,places,name,profile")
            ->where($type,$id)
            ->get()
            ->getResult();

        $charts= [];

        foreach ($specs as $spec) {
            $list = $this->db
                ->table("dataSpec")
                ->where("op",       $spec->id)
                ->where("day!=",    "all")
                ->get()
                ->getResult();

            $total = $this->db
                ->table("dataSpec")
                ->where("op",       $spec->id)
                ->where("day",    "all")
                ->get()
                ->getFirstRow();

            $charts[]= (object)[
                "list"  => $list,
                "total" => $total,
                "chart" => $this->afc
                    ->getDatasetsFormDetailChart(
                        $list,
                        "spec$spec->id",
                        "   $spec->code",
                        $this->dates)
            ];

        }
        $pageContent= view("public/AFC/Details",[
            "charts"      => $charts,
        ]);

        $includes=(object)[
            'js'=>[
            ],
            'css'=>[
                "css/public/details.css"
            ],
        ];

        return view("public/page",[
            "pageContent"   =>  $pageContent,
            "includes"      =>  $includes,
        ]);
    }

}